package com.jzbwlkj.leifeng.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jzbwlkj.leifeng.ui.bean.MySelfModel;

import com.jzbwlkj.leifeng.dao.MySelfModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mySelfModelDaoConfig;

    private final MySelfModelDao mySelfModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mySelfModelDaoConfig = daoConfigMap.get(MySelfModelDao.class).clone();
        mySelfModelDaoConfig.initIdentityScope(type);

        mySelfModelDao = new MySelfModelDao(mySelfModelDaoConfig, this);

        registerDao(MySelfModel.class, mySelfModelDao);
    }
    
    public void clear() {
        mySelfModelDaoConfig.clearIdentityScope();
    }

    public MySelfModelDao getMySelfModelDao() {
        return mySelfModelDao;
    }

}
